import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from "@/app/page.module.css" // css module 사용. 최근은 tailwind + tw-merge +cva 조합도 사용

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = {
  children: React.ReactNode,
};
// 최상위 레이아웃의 children에는 app폴더 하위에 정의된 page.tsx 컴포넌트가 랜더링된다.
export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          {children}
        </div>
      </body>
    </html>
  )
}
